{% set version = "3.0.2" %}
{% set sha256 = "73eb8262b84527a90822404e7504f69081854759806830d402ea1e92176f32a6" %}

package:
  name: reuse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/reuse/reuse-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  entry_points:
    - reuse = reuse._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - poetry-core
  run:
    - binaryornot
    - boolean.py
    - jinja2
    - license-expression
    - python >={{ python_min }}
    - python-debian
    - requests
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - reuse
  commands:
    - reuse --help

about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: reuse is a tool for compliance with the REUSE recommendations.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
    - traversaro
