{% set version = "6.1.2" %}

package:
  name: reuse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/reuse/reuse-{{ version }}.tar.gz
  sha256: 6019a75f4ca18ad5b2506e0f3ec1b926b27ba6cdc9da88492e7fc65e3ff12c39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - reuse = reuse.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.1.0
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=23.2
    - click >=8.1
    - jinja2 >=3.0.0
    - license-expression >=21.6.14
    - tomlkit >=0.8
    - python-debian >=0.1.48
    - python-magic >=0.4.12

    # optionals
    - charset-normalizer >=2.0.5
    - chardet >=3.0.2
    - boolean.py >=3.8
    - binaryornot >=0.4.4

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - reuse
  commands:
    - pip check
    - reuse --help

about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: reuse is a tool for compliance with the REUSE recommendations.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
    - traversaro
    - anjos
