{% set version = "3.0.0" %}
{% set sha256 = "97b85d65f358e4da5338c45bc9d06f711e105d4fb761a9ee9f3f2bf95af5eb91" %}

package:
  name: reuse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/reuse/reuse-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - reuse = reuse._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - poetry-core
  run:
    - binaryornot
    - boolean.py
    - jinja2
    - license-expression
    - python >=3.6
    - python-debian
    - requests
    - setuptools

test:
  imports:
    - reuse
  commands:
    - reuse --help

about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: reuse is a tool for compliance with the REUSE recommendations.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
    - traversaro
