{% set version = "5.1.0" %}

package:
  name: reuse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/reuse/reuse-{{ version }}.tar.gz
  sha256: 33292b44a9f78340bb8ccd37536d7b19d9b9158856841508b63028cae24753b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - reuse = reuse.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.1.0
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.3
    - click >=8.0
    - binaryornot >=0.4.4
    - boolean.py >=3.8
    - jinja2 >=3.0.0
    - license-expression >=1.0
    - tomlkit >=0.8
    - python-debian >=0.1.34,!=0.1.45,!=0.1.46,!=0.1.47

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - reuse
  commands:
    - pip check
    - reuse --help

about:
  home: https://reuse.software/
  license: GPL-3.0-or-later AND Apache-2.0 AND CC0-1.0 AND CC-BY-SA-4.0
  license_file:
    - LICENSES/GPL-3.0-or-later.txt
    - LICENSES/Apache-2.0.txt
    - LICENSES/CC0-1.0.txt
    - LICENSES/CC-BY-SA-4.0.txt
  summary: reuse is a tool for compliance with the REUSE recommendations.
  doc_url: https://reuse.readthedocs.io/
  dev_url: https://github.com/fsfe/reuse-tool

extra:
  recipe-maintainers:
    - mbargull
    - traversaro
    - anjos
